<h4>Data Glossary</h4>
<ul class="sub-menu">
  <li class="menu-item"><a href="https://www.datalinker.org/legal">Legal</a></li>
  <li class="menu-item"><a class="active" href="https://www.datalinker.org/biophysical">Biophysical</a></li>
  <li class="menu-item"><a href="https://www.datalinker.org/management">Management</a></li>
  <li class="menu-item"><a href="https://www.datalinker.org/outcome-metrics">Outcome Metrics</a></li>
</ul>
<hr>

<h2 id="datalinker">Biophysical</h2>
<p></p>
